### ISSUE TITLE
Laravel  5.6.35 composer require fails

### ISSUE THREAD

**Issue by AbdulRafay** [vinkla/laravel-facebook#14]
While installing vinkla for laravel 5.6.35 i get the following error:

  Problem 1
    - Conclusion: remove laravel/framework v5.6.35
    - Conclusion: don't install laravel/framework v5.6.35
    - vinkla/facebook 3.1.0 requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev].
    - vinkla/facebook 3.1.x-dev requires illuminate/support 5.7.* -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev].
    - Can only install one of: laravel/framework[5.7.x-dev, v5.6.35].
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v5.6.35
    - Installation request for laravel/framework (locked at v5.6.35, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.35].
    - Installation request for vinkla/facebook ^3.1 -> satisfiable by vinkla/facebook[3.1.0, 3.1.x-dev].

is there any workaround available for this issue?

**Comment by vinkla** [comment]
Try installing version `3.0.0` of this package.
