### ISSUE TITLE
Problem on production server

### ISSUE THREAD

**Issue by Enitnelav** [vinkla/laravel-facebook#16]
Hi, 

we have a problem when we deploy our app on production server, 

the error is 'class facebook does'nt exist' but locaaly no poblem,

we tried a lot of things, have you an idea ?

**Comment by vinkla** [comment]
No.

> _When a person reviews an Issue Request there should be enough information that they have a good handle of what is being discussed, they don’t need to know or come up with a solution instantly, but nothing about the issue should be mystery meat - [UpThemes](https://upthemes.com/blog/2014/02/writing-useful-github-issues/)_

**Comment by Enitnelav** [comment]
here the part of our code where we call your class Facebook,

```
use Vinkla\Facebook\Facades\Facebook;

class Reseaux_sociaux extends Model
{

    public function get_likes_facebook()
    {

        //On récupère la valeur en ligne
        try {
            $facebook_object = Facebook::get('/19*********?fields=fan_count');
            $facebook_body = json_decode($facebook_object->getBody(), true);
            $nb_likes_facebook = $facebook_body['fan_count'];
        } catch (Exception $e) {
            $nb_likes_facebook = 0;
        }

        // On multiplie en fonction de la valeur d'un like
        $nb_likes_facebook = (empty($nb_likes_facebook) ? 0 : $nb_likes_facebook) * Config::get('courses.multiplicateur_like_facebook');

        return $nb_likes_facebook;

    }
```

**Comment by vinkla** [comment]
Don't see any issues. Sorry.
