### ISSUE TITLE
Login/auth via laravel-facebook

### ISSUE THREAD

**Issue by rzelnik** [vinkla/laravel-facebook#17]
Is there any easy way to use this bridge for login/auth process, or should I rather combine it with Socialite? I would like to login/authenticate the web user through Facebook, then get it's user access token and get some data from Facebook using the user access token.

**Comment by vinkla** [comment]
This is possible with this package. Please see the [login example](https://github.com/facebook/php-graph-sdk/blob/ff0226eec0661d10221f32f0076d1da43f8ea69b/docs/examples/facebook_login.md) from the documentation.
