### ISSUE TITLE
Runtime configuration

### ISSUE THREAD

**Issue by donmarkus** [vinkla/laravel-facebook#8]
Hi this is not really an issue im looking for a way to set facebook params dynamically. can you help 

Like this

`$facebook = new Facebook([
            'app_id' => $client_id,
            'app_secret' => $client_secret,
            'default_graph_version' => 'v2.6',
   ]);`

**Comment by vinkla** [comment]
Then you don't need this library. You can use the [`facebook/php-graph-sdk`](https://github.com/facebook/php-graph-sdk) directly and create new `Facebook` instances manually.

**Comment by donmarkus** [comment]
Thanks for the quick answer
